<?php

namespace AppBundle\Entity;

/**
 * CommentRatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRatingsRepository extends \Doctrine\ORM\EntityRepository
{
}
